[package]
name = "model_checker"
version = "0.1.0"
authors = ["Nanne Wielinga <nanne@mycel.nl>"]
build = "build.rs"
build_lib = false

[build-dependencies]
peg = { version = "0.5" }

[dependencies]
# petgraph = "0.4.3"
boolean_expression = "0.3.0"
rustyline = { git = "https://github.com/kkawakam/rustyline" }

